Test coverage >=80%
radars-app/radars-app pull request #5
Opened 2020-10-26 13:01 UTC by kalachou

2020-10-26 13:20 UTC, vladimir-sviridenko requested changes

2020-10-26 13:20 UTC, vladimir-sviridenko commented on src-fe/src/app/container/store/sample/sample.reducer.spec.ts
> +			const result: any = reducer(initialState, action);
Get rid of 'any' types, if possible, please

2020-10-26 13:20 UTC, vladimir-sviridenko commented on src-fe/src/app/container/store/sample/sample.actions.spec.ts
> +	it('should create an instance', () => {
There is three similar test description. Maybe better to write 'should create an instance of LoadSamplesFailure'.
The same below.

2020-10-26 13:20 UTC, vladimir-sviridenko commented on src-fe/src/app/container/store/sample/sample.effects.ts
> +// 	);
Remove commented code

2020-10-26 14:55 UTC, clain-atomi commented on src-fe/src/app/container/store/sample/sample.reducer.spec.ts
> +			const result: any = reducer(initialState, action);
fixed?

2020-10-26 16:16 UTC, clain-atomi requested changes

2020-10-26 16:16 UTC, clain-atomi commented on src-fe/src/app/container/store/sample/sample.actions.spec.ts
> +	it('should create an instance LoadSamplesFailure', () => {
add new line between `it` and `describe` statements

2020-10-27 14:25 UTC, clain-atomi approved these changes

2020-10-28 10:26 UTC, vladimir-sviridenko approved these changes

2020-10-29 15:20 UTC, merged