[P1] Radar Card Common Component
radars-app/radars-app pull request #57
Opened 2020-12-21 14:36 UTC by kalachou

2020-12-22 09:49 UTC, vladimir-sviridenko approved these changes

2020-12-24 11:11 UTC, clain-atomi requested changes

2020-12-24 11:11 UTC, clain-atomi commented on src-fe/src/app/libs/radars-general-view/radars-general-view.component.html
> +				<app-general-radar-chart [radar]="radar" [radarDataItems]="radarDataItems[index]" *ngIf="radar && radarDataItems[index]"></app-general-radar-chart>
lets move ngIf expression to method inside component

2020-12-24 11:11 UTC, clain-atomi commented on src-fe/src/app/libs/radars-general-view/store/radars-general-view/radars-general-view.effects.ts
> +			return this.radarsGeneralViewRepositoryService.loadAllLatestRadars().pipe(
too long name, lets use at least `this.radarsGeneralViewRepository`

2020-12-24 11:11 UTC, clain-atomi commented on src-fe/src/app/libs/radars-general-view/store/radars-general-view/radars-general-view.reducer.ts
> +	action: RadarsGeneralViewActions
lets try to simplify it to one line

2020-12-24 11:11 UTC, clain-atomi commented
can be merged after fix

2020-12-24 11:54 UTC, kalachou commented on src-fe/src/app/libs/radars-general-view/store/radars-general-view/radars-general-view.reducer.ts
> +	action: RadarsGeneralViewActions
line-max-length is exceeded in the case

2020-12-24 15:10 UTC, merged