Create button
radars-app/radars-app pull request #72
Opened 2021-01-14 13:33 UTC by vladimir-sviridenko

![image](https://user-images.githubusercontent.com/57321079/104597352-464d2780-5686-11eb-9119-6f5fb367a4dd.png)

2021-01-14 14:13 UTC, clain-atomi requested changes

2021-01-14 14:13 UTC, clain-atomi commented on src-fe/src/app/libs/container/components/global-header/global-header.component.html
> +	<app-button [theme]="createRadarButtonTheme"  *ngIf="isRootPageOpened">
1 unnecessary space here

2021-01-14 14:13 UTC, clain-atomi commented on src-fe/src/app/libs/container/components/global-header/global-header.component.html
> +		<app-icon class="container-header__icon--plus" icon="plus"></app-icon>
container-header--create-icon

2021-01-15 11:43 UTC, vladimir-sviridenko commented on src-fe/src/app/libs/container/components/global-header/global-header.component.html
> +		<app-icon class="container-header__icon--plus" icon="plus"></app-icon>
I guess you mean container-header__create-icon

2021-01-15 12:07 UTC, merged