feat: add radar history slider
radars-app/radars-app pull request #92
Opened 2021-04-05 11:33 UTC by MaxProtos

2021-04-05 14:25 UTC, clain-atomi requested changes

2021-04-05 14:25 UTC, clain-atomi commented on src-fe/src/app/libs/common-components/radar-date-switcher/radar-date-switcher.component.ts
> +	private destroy$: Subject<boolean> = new Subject<boolean>();
Subject`<void>`

2021-04-05 14:25 UTC, clain-atomi commented on src-fe/src/app/libs/common-components/radar-date-switcher/radar-date-switcher.component.ts
> +		this.destroy$.next(true);
.next()

2021-04-05 14:25 UTC, clain-atomi commented on src-fe/src/app/libs/common-components/radar-date-switcher/radar-date-switcher.component.ts
> +	private updateRouteQueryParams(date: Date): void {
updateDateInUrl

2021-04-05 14:25 UTC, clain-atomi commented on src-fe/src/app/libs/common-components/radar-date-switcher/radar-date-switcher.component.ts
> +		const dateParam: string = `${date.getUTCFullYear()}-${
date param = date.toUtcString()

2021-04-05 14:25 UTC, clain-atomi commented on src-fe/src/app/libs/common-components/radar-date-switcher/radar-date-switcher.component.ts
> +	private updateRadarDateFromUrlParams(date: string, radarId: string): void {
updateRadarDateFromUrl

2021-04-05 14:25 UTC, clain-atomi commented on src-fe/src/app/libs/common-components/radar-date-switcher/radar-date-switcher.component.ts
> +		const dateFromParams: number = parseInt(dateAsArray[2], 10);
parsedDate: Date = new Date(date);

2021-04-05 14:25 UTC, clain-atomi commented on src-fe/src/app/libs/radar-view/components/radar-chart/radar-chart.component.html
> +<app-zoom-in-out-panel	class="radar-chart__zoom-in-out"
align indentation

2021-04-05 14:25 UTC, clain-atomi commented on src-fe/src/app/libs/radar-view/components/radar-chart/radar-chart.component.scss
> +		right: calc(#{$gutter-width} + 70px);
70px = $secondary-grid-unit * ...

2021-04-05 14:25 UTC, clain-atomi commented on src-fe/src/app/libs/radar-view/store/radar-view/radar-view.actions.ts
> +	constructor(public radarId: string, public date?: Date) {}
merge to single param

2021-04-05 14:25 UTC, clain-atomi commented on src-fe/src/app/libs/radar-view/store/radar-view/radar-view.actions.ts
> +	constructor(public radarId: string, public date?: Date) {}
date is not optional

2021-04-05 14:25 UTC, clain-atomi commented on src-fe/src/app/libs/radar-view/store/radar-view/radar-view.effects.ts
> +			const dateToLoad: Date = action.date ?? radarDate;
selectedDate

2021-04-05 14:25 UTC, clain-atomi commented on src-fe/src/app/libs/radar-view/store/radar-view/radar-view.effects.ts
> +		withLatestFrom(this.radarViewFacadeService.radar$),
add filter pipe to check that radar is exists

2021-04-05 14:25 UTC, clain-atomi commented on src-fe/src/app/libs/radar-view/store/radar-view/radar-view.reducer.ts
> +			const dateFromQueryParams: Date = (action as LoadRadar).date ?? null;
selectedDate

2021-04-06 06:05 UTC, MaxProtos commented on src-fe/src/app/libs/common-components/radar-date-switcher/radar-date-switcher.component.html
> +					  icon="arrow-left3">
![1](https://user-images.githubusercontent.com/46648766/113666058-46722780-96b7-11eb-8907-ee5314176581.png)
github issues

2021-04-06 08:51 UTC, clain-atomi requested changes

2021-04-06 08:51 UTC, clain-atomi commented on src-fe/src/app/libs/radar-view/components/date-switcher/date-switcher.component.html
> +<div class="date-switcher" [class.date-switcher--dark-theme]="(theme$ | async) === 'dark'">
move to getter `(theme$ | async) === 'dark'"` also better use `theme` as @Input to allow change theme dynamically

2021-04-06 11:52 UTC, clain-atomi approved these changes

2021-04-06 11:52 UTC, merged