Refactor/radar search
radars-app/radars-app pull request #94
Opened 2021-04-13 14:17 UTC by MaxProtos

2021-04-13 14:58 UTC, clain-atomi requested changes

2021-04-13 14:58 UTC, clain-atomi commented on src-fe/src/app/libs/common-components/radar-search/radar-search.component.html
> +			<small class="radar-search__option-content"
why not div here?

2021-04-13 14:58 UTC, clain-atomi commented on src-fe/src/app/libs/common-components/text-input/text-input.theme.scss
> -
can we remove this component from our codebase completely?

2021-04-13 14:58 UTC, clain-atomi commented on src-fe/src/app/libs/radar-view/radar-view.component.ts
> +			this.autoCompleteOptions = [];
Or even handle this in parent function, to keep this function do 1 thing

2021-04-13 14:58 UTC, clain-atomi commented on src-fe/src/app/libs/radar-view/radar-view.component.ts
> +	private cutOptionsContentFromQueryEntry(content: string, query: string): string {
generally lets move all logic related to autocomplete calculation to separate service, radar view becomes fat controller

2021-04-14 06:02 UTC, MaxProtos commented on src-fe/src/app/libs/common-components/radar-search/radar-search.component.html
> +				  disableRipple="true">
![Untitled](https://user-images.githubusercontent.com/46648766/114661703-1999c200-9d00-11eb-9ca1-743bab0e64e2.png)
github troubles

2021-04-14 06:20 UTC, MaxProtos commented on src-fe/src/app/libs/common-components/text-input/text-input.theme.scss
> -
not yet. It uses in others components

2021-04-14 07:30 UTC, clain-atomi requested changes

2021-04-14 07:30 UTC, clain-atomi commented on src-fe/src/app/libs/common-components/radar-search/radar-search.component.html
> +				  disableRipple="true">
indentation

2021-04-14 07:30 UTC, clain-atomi commented on src-fe/src/app/libs/common-components/radar-search/radar-search.component.scss
> +}
.radar-search-input-dark { .radar-search__search-icon { ... } ...}

2021-04-14 07:30 UTC, clain-atomi commented on src-fe/src/app/libs/common-components/radar-search/radar-search.component.ts
> +		return this.theme === 'dark';
this.theme === ComponentTheme.Dark

2021-04-14 07:48 UTC, clain-atomi approved these changes

2021-04-14 07:52 UTC, merged